CREATE OR REPLACE DATABASE feast_spcs_redis;
DROP SCHEMA PUBLIC;
CREATE OR REPLACE SCHEMA feature_store;
CREATE OR REPLACE IMAGE REPOSITORY feast_spcs_redis_image;
CREATE OR REPLACE STAGE feast_spcs_redis_stage
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE COMPUTE POOL feast_spcs_redis
MIN_NODES = 1 --we will guarantee you this
MAX_NODES = 5 --we will take you up to this max
INSTANCE_FAMILY = HIGHMEM_X64_M --32cpu 256ram
AUTO_RESUME = TRUE
AUTO_SUSPEND_SECS = 1000000;
SHOW COMPUTE POOLS;

DROP SERVICE feast_spcs_redis;
CREATE SERVICE feast_spcs_redis
IN COMPUTE POOL feast_spcs_redis
FROM @feast_spcs_redis_stage
SPECIFICATION_FILE='/spcs/manifest.yaml'
MIN_INSTANCES=1
MAX_INSTANCES=6
EXTERNAL_ACCESS_INTEGRATIONS = (OPEN_ACCESS_INTEGRATION);

CALL SYSTEM$GET_SERVICE_STATUS('FEAST_SPCS_REDIS');
CALL SYSTEM$GET_SERVICE_LOGS('FEAST_SPCS_REDIS', '0', 'feastserver', 1000);
CALL SYSTEM$GET_SERVICE_LOGS('FEAST_SPCS_REDIS', '0', 'redis', 1000);
CALL SYSTEM$GET_SERVICE_LOGS('FEAST_SPCS_REDIS', '0', 'vscode', 1000);

SHOW ENDPOINTS IN SERVICE feast_spcs_redis;
